<div class="container mx-auto">
<div class="lg:mt-48 dark:text-white transition ease-in-out duration-500">
    <h2 class="lg:text-4xl lg:leading-13  lg:my-10 font-bold " >Τίτλος 1</h2>
    <p class="lg:text-3xl lg:leading-13  lg:my-10">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tempor orci dapibus ultrices in iaculis nunc. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula ipsum. Pulvinar mattis nunc sed blandit libero. Enim ut tellus elementum sagittis vitae et leo duis. Ut venenatis tellus in metus vulputate eu scelerisque. Sed nisi lacus sed viverra tellus. Aliquam ultrices sagittis orci a scelerisque. Est velit egestas dui id ornare arcu odio ut. Mattis molestie a iaculis at erat pellentesque. Orci porta non pulvinar neque. Egestas purus viverra accumsan in nisl nisi. Commodo sed egestas egestas fringilla phasellus. Maecenas accumsan lacus vel facilisis volutpat est velit egestas. Justo donec enim diam vulputate ut.Vitae congue mauris rhoncus aenean vel. At tempor commodo ullamcorper a lacus vestibulum sed. Curabitur gravida arcu ac tortor dignissim. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit aliquam. Pretium vulputate sapien nec sagittis aliquam </p>
    <h2 class="lg:text-4xl lg:leading-13  lg:my-10 font-bold">Τίτλος 2</h2>
    <p class="lg:text-3xl lg:leading-13  lg:my-10">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tempor orci dapibus ultrices in iaculis nunc. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula ipsum. Pulvinar mattis nunc sed blandit libero. Enim ut tellus elementum sagittis vitae et leo duis. Ut venenatis tellus in metus vulputate eu scelerisque. Sed nisi lacus sed viverra tellus. Aliquam ultrices sagittis orci a scelerisque. Est velit egestas dui id ornare arcu odio ut. Mattis molestie a iaculis at erat pellentesque. Orci porta non pulvinar neque. Egestas purus viverra accumsan in nisl nisi. Commodo sed egestas egestas fringilla phasellus. Maecenas accumsan lacus vel facilisis volutpat est velit egestas. Justo donec enim diam vulputate ut.Vitae congue mauris rhoncus aenean vel. At tempor commodo ullamcorper a lacus vestibulum sed. Curabitur gravida arcu ac tortor dignissim. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit aliquam. Pretium vulputate sapien nec sagittis aliquam </p>
    <h2 id="part-three" class="lg:text-4xl lg:leading-13  lg:my-10 font-bold">Τίτλος 3</h2>
    <p class="lg:text-3xl lg:leading-13  lg:my-10">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tempor orci dapibus ultrices in iaculis nunc. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula ipsum. Pulvinar mattis nunc sed blandit libero. Enim ut tellus elementum sagittis vitae et leo duis. Ut venenatis tellus in metus vulputate eu scelerisque. Sed nisi lacus sed viverra tellus. Aliquam ultrices sagittis orci a scelerisque. Est velit egestas dui id ornare arcu odio ut. Mattis molestie a iaculis at erat pellentesque. Orci porta non pulvinar neque. Egestas purus viverra accumsan in nisl nisi. Commodo sed egestas egestas fringilla phasellus. Maecenas accumsan lacus vel facilisis volutpat est velit egestas. Justo donec enim diam vulputate ut.Vitae congue mauris rhoncus aenean vel. At tempor commodo ullamcorper a lacus vestibulum sed. Curabitur gravida arcu ac tortor dignissim. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit aliquam. Pretium vulputate sapien nec sagittis aliquam </p>
    <figure >
        <img class="mx-auto mb-5" src="/storage/images/featured-blog-img.jpg">
        <figcaption class="text-center text-xl">Fig.1 - Trulli, Puglia, Italy.</figcaption>
    </figure>
    <h2 class="lg:text-4xl lg:leading-13  lg:my-10 font-bold">Τίτλος 4</h2>
    <p class="lg:text-3xl lg:leading-13  lg:my-10">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tempor orci dapibus ultrices in iaculis nunc. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula ipsum. Pulvinar mattis nunc sed blandit libero. Enim ut tellus elementum sagittis vitae et leo duis. Ut venenatis tellus in metus vulputate eu scelerisque. Sed nisi lacus sed viverra tellus. Aliquam ultrices sagittis orci a scelerisque. Est velit egestas dui id ornare arcu odio ut. Mattis molestie a iaculis at erat pellentesque. Orci porta non pulvinar neque. Egestas purus viverra accumsan in nisl nisi. Commodo sed egestas egestas fringilla phasellus. Maecenas accumsan lacus vel facilisis volutpat est velit egestas. Justo donec enim diam vulputate ut.Vitae congue mauris rhoncus aenean vel. At tempor commodo ullamcorper a lacus vestibulum sed. Curabitur gravida arcu ac tortor dignissim. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit aliquam. Pretium vulputate sapien nec sagittis aliquam </p>
    <ol class="lg:text-3xl lg:leading-13  lg:my-10 list-decimal font-bold">
        <li>First thing <p class="font-normal">Mia epeksgisi gia to ti einai to first thing</p></li>
        <li>Second thing</li>
        <li>Third thing</li>


    </ol>

</div>
</div>
